IMS.Web/Controllers/Add_OutwardMaterialController.cs
using IMS.BLL;
using IMS.BLL.Interfaces;
using IMS.DAL;
using IMS.Entities;
using IMS.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Data.Entity;
using System.Threading.Tasks;

namespace IMS.Web.Controllers
{
    public class Add_OutwardMaterialController : Controller
    {
        // GET: Add_OutwardMaterial
        private ServiceVMSEntities context = new ServiceVMSEntities();
        private UnitOfWork unitOfWork = new UnitOfWork();
        private IMExceptionLogger exceptionLogger = BLLObjectCreator.CreateIMSLogger(ExceptionLoggerType.IMSText);

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OutwardList(string sortOrder, string searchString, string Name, string SearchValue1, string SearchValue2, string SearchValue, string SearchValue_ExpenseN, FormCollection form, DateTime? searchdate, int? Page_no)
        {
            string role = null;
            if (Session["role"] != null)
            {
                role = Session["role"].ToString();
            }
            if (role != null)
            {
                string location = null;
                int pagesize = 20;
                int pagenumber = (Page_no ?? 1);
                ViewBag.page = Page_no;

                int countForsearch = 0;
                string display = "0";
                ViewBag.display = display;
                int count = 0;
                string empid = null;
                DateTime val = DateTime.Now;

                if (searchdate.HasValue)
                {
                    val = searchdate ?? DateTime.Now;

                }
                if (Session["Location"] != null)
                {
                    location = Session["Location"].ToString();
                    ViewBag.location = Session["Location"].ToString();
                }

                ViewBag.Outward_no = sortOrder == "outwardNo_asc" ? "outwardNo_desc" : "outwardNo_asc";
                ViewBag.Gatepass_Number = sortOrder == "gatepassNo_asc" ? "gatepassNo_desc" : "gatepassNo_asc";
                ViewBag.Department = sortOrder == "dept_asc" ? "dept_desc" : "dept_asc";
                ViewBag.Location = sortOrder == "loc_asc" ? "loc_desc" : "loc_asc";
                ViewBag.OutwardDatetime = sortOrder == "datetime_asc" ? "datetime_desc" : "datetime_asc";
                ViewBag.ReceiverName = sortOrder == "receiver_asc" ? "receiver_desc" : "receiver_asc";
                ViewBag.OutwardStatus = sortOrder == "status_asc" ? "status_desc" : "status_asc";

                if (Session["UserID"] != null)
                {
                    empid = Session["UserID"].ToString();
                    ViewBag.userid = empid;
                }


                string dept = null;

                if (Session["DepartmentID"] != null)
                {
                    dept = Session["DepartmentID"].ToString();

                }
                ViewBag.role = role;
                var imsentity = new List<IMSEntity>();


                //ViewBag.empid = empid;
                try
                {
                    ServiceVMSEntities context = new ServiceVMSEntities();
                    var serviceuser = new ServiceUserDepartment();
                    var name_department = unitOfWork.DepartmentRepository.Get(serviceuser, int.Parse(dept));
                    string deptName = name_department[0].userDepartmentName;




                    var OutwardDetails = (from t in context.OutwardMaterials
                                          join g in context.GatePasses on t.GatepassID equals g.GatepassID
                                          join d in context.ServiceUserDepartments on g.userDepartmentId equals d.userDepartmentId
                                          where t.Outward_Status != "Deleted"
                                          select new
                                          {
                                              t.OW_MaterialID,
                                              t.Outward_Status,
                                              t.OutwardDatetime,
                                              t.OutwardNote,
                                              g.Location,
                                              g.userDepartmentId,
                                              g.GatepassType,
                                              g.Gatepass_Number,
                                              g.ReceiverID,
                                              g.ReceiverName,
                                              d.userDepartmentName,
                                              t.OutwardNo
                                          });
                    if (empid != null)
                    {
                        if (empid.Contains("DUM"))
                        {
                            if (role == "Inventory Manager")
                            {
                                OutwardDetails = OutwardDetails.Where(u => u.OW_MaterialID.Contains("DUM"));

                            }
                            else
                            {
                                OutwardDetails = OutwardDetails.Where(u => u.OW_MaterialID.Contains("DUM") && u.userDepartmentId == int.Parse(dept));
                            }


                        }
                        else
                        {
                            var cc = OutwardDetails.Count();
                            int deptid = int.Parse(dept);
                            if (role == "Administrator")
                            {
                                OutwardDetails = OutwardDetails.Where(u => !u.OW_MaterialID.Contains("DUM"));
                            }
                            else if (role == "Inventory Manager")
                            {
                                OutwardDetails = OutwardDetails.Where(u => !u.OW_MaterialID.Contains("DUM") && u.userDepartmentId == deptid);
                            }
                            else if (role == "Security Guard")
                            {
                                OutwardDetails = OutwardDetails.Where(u => !u.OW_MaterialID.Contains("DUM") && u.Location == location);
                            }
                            else if (role == "Inventory Incharge" || role == "Receiver")
                            {
                                OutwardDetails = OutwardDetails.Where(u => !u.OW_MaterialID.Contains("DUM") && u.Location == location && u.userDepartmentId == deptid);
                            }
                            else
                            {

                                OutwardDetails = OutwardDetails.Where(u => !u.OW_MaterialID.Contains("DUM") && u.userDepartmentId == deptid);
                            }
                        }
                    }
                    var c = OutwardDetails.Count();

                    if (Name == "actionable")
                    {
                        if (role == "Security Guard")
                        {
                            OutwardDetails = OutwardDetails.Where(u => u.Outward_Status == "Material Out");
                        }
                    }
                    if (!String.IsNullOrEmpty(SearchValue) || !String.IsNullOrEmpty(SearchValue_ExpenseN) || !String.IsNullOrEmpty(SearchValue1) || searchdate != null)
                    {
                        String Searchby = form["Name"].ToString();

                        if (Searchby == "Outward_id")
                        {
                            countForsearch = 1;
                            OutwardDetails = OutwardDetails.Where(u => u.OW_MaterialID.Contains(SearchValue));
                        }
                        else if (Searchby == "Outward_department")
                        {
                            countForsearch = 1;
                            int DepartmentName;
                            var InwardValue = (from i in context.ServiceUserDepartments
                                               where i.userDepartmentName == SearchValue1
                                               select new { i.userDepartmentId }).ToList();
                            foreach (var t in InwardValue)
                            {
                                DepartmentName = t.userDepartmentId;
                                OutwardDetails = OutwardDetails.Where(u => u.userDepartmentId == DepartmentName);
                            }
                        }
                        else if (Searchby == "Outward_Location")
                        {
                            countForsearch = 1;
                            OutwardDetails = OutwardDetails.Where(u => u.Location.Contains(SearchValue));
                        }
                        else if (Searchby == "OutwardStatus")
                        {
                            countForsearch = 1;
                            OutwardDetails = OutwardDetails.Where(u => u.Outward_Status.Contains(SearchValue));
                        }
                        else if (Searchby == "OutwardDatetime" && (searchdate != null))
                        {
                            countForsearch = 1;
                            val = val.Date;
                            OutwardDetails = OutwardDetails.Where(u => u.OutwardDatetime == (val));
                        }
                    }

                    switch (sortOrder)
                    {
                        case "outwardNo_desc":
                            OutwardDetails = OutwardDetails.OrderByDescending(o => o.OutwardNo);
                            break;
                        case "outwardNo_asc":
                            OutwardDetails = OutwardDetails.OrderBy(o => o.OutwardNo);

IMS.Web/Views/Add_OutwardMaterial/OutwardDetails.cshtml
@{
    ViewBag.Title = "OutwardDetails";
    Layout = "~/Views/Shared/_Layout_IMS.cshtml";
}
<link href="~/assets/css/custom.css" rel="stylesheet" />

<div class="rightpanel-height">
    <div class="d-flex align-items-center justify-content-between">
        <h5 class="content-title mb-3">Outward Details</h5>
        <a class="back-btn d-flex" href="@Url.Action("OutwardList", "Add_OutwardMaterial")">
            <img class="mr-8" src="~/assets/images/icons/back-arrow.svg" /> Back
        </a>
    </div>
    <div class="card card-height">
        <div class="card-body">
            <input type="hidden" name="Gatepasstype" id="gatepasstype" value="@Model.OutwardDetail.GatepassType" />
            <input type="hidden" id="outwardmaterialid" value="@Model.OutwardDetail.OW_MaterialID" />
            <div class="d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center mb-3">
                    <div class="right-space ft-18 gatepass-no">Outward No:</div>
                    <div class="">
                        <p class="form-control-plaintext ft-18 gatepass-no">@Model.OutwardDetail.OutwardNo</p>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-md-12">
                    <table class="gatepass-table">
                        <thead>
                            <tr>
                                <th class="col-lg-2">Gatepass Number</th>
                                <th class="col-lg-2">Outward Date</th>
                                <th class="col-lg-2">Receiver Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>@Model.OutwardDetail.Gatepass_Number</td>
                                <td>@Model.OutwardDetail.OutwardDatetime.ToString("dd MMM yyyy")</td>
                                <td>@Model.OutwardDetail.ReceiverName</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <h5 class="mb-3 items">Items</h5>

            <!-- Table to display materials -->
            <table class="table outwarddetail-table">
                <thead class="border-btm">
                    <tr>
                        <th>Asset ID</th>
                        <th>Expense Nature</th>
                        <th>Material Name</th>
                        <th>Model No</th>
                        <th>Serial No</th>
                        <th>GRN Number</th>
                        <th>Status</th>
                        @if (Model.OutwardDetail.GatepassType != "NonReturnable")
                        {
                            <th>Received</th>
                        }
                        </tr>
                </thead>
                <tbody>
                    @if (Model.MaterialItems != null)
                    {
                        foreach (var item in Model.MaterialItems)
                        {
                            <tr>
                                <td>@item.AssetId</td>
                                <td>@item.ExpenseNature</td>
                                <td>@item.MaterialName</td>
                                <td>@item.ModelNo</td>
                                <td>@item.SerialNo</td>
                                <td>@item.GRN_Number</td>
                                <td>@item.OutStatus</td>
                                @if (Model.OutwardDetail.GatepassType != "NonReturnable")
                                {
                                    <td>
                                        <input type="checkbox" class="received-checkbox" data-outmat-id="@item.OutMat_ID" @(item.OutStatus == "Material In" ? "disabled" : "") />
                                    </td>
                                }
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="8" class="text-center">No materials found for this Outward Material ID.</td>
                        </tr>
                    }
                </tbody>
            </table>



            <!-- Buttons for cancel and save -->
            <div class="border-top"></div>


            <div class="text-right mt-5">
                <a href="@Url.Action("OutwardList", "Add_OutwardMaterial")" class="button cancel-btn">Cancel</a>
                @if (Model.OutwardDetail.GatepassType != "NonReturnable")
                {
                    <button id="save-button" class="action-btn">Save</button>
                }
                </div>
        </div>
    </div>
</div>

<!-- Ensure jQuery is loaded -->
<script src="~/assets/libs/jquery/dist/jquery.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        // Function to check if all checkboxes are disabled
        function checkAllCheckboxes() {
            var allDisabled = $('.received-checkbox').length === $('.received-checkbox:disabled').length;
            $('#save-button').prop('disabled', allDisabled); // Disable save button if all checkboxes are disabled
        }

        // Run check on page load
        checkAllCheckboxes();

        // When the save button is clicked
        $('#save-button').click(function () {
            var selectedOutMatIds = [];
            var gatePassID = ''; // Assuming all items belong to the same GatePassID

            // Collect all checked materials
            $('.received-checkbox:checked').each(function () {
                selectedOutMatIds.push($(this).data('outmat-id'));
            });

            // Ensure that some checkboxes are checked before making the call
            if (selectedOutMatIds.length > 0) {
                // Make an AJAX call to send selected OutMat_IDs to the server
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("MarkAsReceived", "Add_OutwardMaterial")',
                    data: {
                        outMatIds: selectedOutMatIds, // Array of OutMat_IDs
                        gatepassID: '@Model.OutwardDetail.GatepassID' // Single GatePassID
                    },
                    success: function (response) {
                        debugger;
                        var url = '@Url.Action("OutwardDetails", "Add_OutwardMaterial")';
                        var OID = $("#outwardmaterialid").val();
                        if (response.message == "success") {
                            alert("Materials marked as received successfully.");
                            window.location.href = url + '?id=' + OID;
                           // location.reload(); // Reload the page to reflect the updated status
                        } else {
                            alert(response.message);
                        }
                    },
                    error: function () {
                        alert("An error occurred while processing your request.");
                    }
                });
            } else {
                alert("Please select at least one material to mark as received.");
            }
        });
    });
</script>