IMS.Web/Controllers/Add_InventoryRegisterController.cs
using IMS.DAL;
using IMS.Entities;
using IMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Newtonsoft.Json;
using System.IO;
using ExcelDataReader;
using System.Threading;
using ExcelDataReader.Log;
using System.Data.Entity;

namespace IMS.Web.Controllers
{
    public class Add_InventoryRegisterController : Controller
    {
        private ServiceVMSEntities context = new ServiceVMSEntities();
        private UnitOfWork unitOfWork = new UnitOfWork();
        // GET: Add_InventoryRegister
        public ActionResult Index(string sortOrder, string searchString, string Name, string SearchValue1, string SearchValue2, string SearchValue, string SearchValue_ExpenseN, FormCollection form, DateTime? searchdate, int? Page_no)
        {
            var httpCookie3 = Session["role"];
            string role = null;
            if (httpCookie3 != null)
            {
                role = httpCookie3.ToString();
            }
            if (role != null)
            {
                string location = null;
                int countForsearch = 0;
                string display = "0";
                ViewBag.display = display;
                int count = 0;
                string empid = null;
                string Email = null;
                DateTime val = DateTime.Now;
                int pagesize = 20;
                int pagenumber = (Page_no ?? 1);
                ViewBag.page = Page_no;
                if (Session["Location"] != null)
                {
                    location = Session["Location"].ToString();
                    ViewBag.location = Session["Location"].ToString();
                }

                ViewBag.Asset_id = String.IsNullOrEmpty(sortOrder) ? "Asset_id_desc" : "";
                ViewBag.Inv_department = sortOrder == "Inv_department" ? "Inv_department_desc" : "Inv_department";
                ViewBag.Inv_location = sortOrder == "Inv_location" ? "Inv_location_desc" : "Inv_location";
                ViewBag.Inv_nature = sortOrder == "Inv_nature" ? "Inv_nature_desc" : "Inv_nature";
                ViewBag.Mat_category = sortOrder == "Mat_category" ? "Mat_category_desc" : "Mat_category";
                ViewBag.Mat_name = sortOrder == "Mat_name" ? "Mat_name_desc" : "Mat_name";
                ViewBag.vendorId = sortOrder == "vendorId" ? "vendorId_desc" : "vendorId";
                ViewBag.purchaserate = sortOrder == "purchaserate" ? "purchaserate_desc" : "purchaserate";


                var httpCookie1 = Session["UserID"];
                if (httpCookie1 != null)
                {
                    empid = httpCookie1.ToString();
                    ViewBag.empid = empid;
                }


                string dept = null;

                var httpCookie4 = Session["DepartmentID"];
                if (httpCookie4 != null)
                {
                    dept = httpCookie4.ToString();
                }
                ViewBag.role = role;
                var imsentity = new List<IMSEntity>();


                try
                {
                    ServiceVMSEntities context = new ServiceVMSEntities();
                    var serviceuser = new ServiceUserDepartment();
                    var name_department = unitOfWork.DepartmentRepository.Get(serviceuser, int.Parse(dept));
                    string deptName = name_department[0].userDepartmentName;


                    IQueryable<IMSEntity> InventoryDetails = null;

                    InventoryDetails = (from t in context.Inventory_Register
                                        join i in context.InwardMaterials on t.InwardID equals i.InwardID into inwardGroup
                                        from i in inwardGroup.DefaultIfEmpty()
                                        join cat in context.Material_Category on t.Material_CategoryID equals cat.Material_CategoryID into catGroup
                                        from cat in catGroup.DefaultIfEmpty()
                                        join m in context.Materials on t.MaterialID equals m.MaterialID into materialGroup
                                        from m in materialGroup.DefaultIfEmpty()
                                        join v in context.HTV_Vendor on t.vendorId equals v.vendorId into vendorGroup
                                        from v in vendorGroup.DefaultIfEmpty()
                                        join tv in context.TempVendors on t.vendorId equals tv.TempVendorID into tempVendorGroup
                                        from tv in tempVendorGroup.DefaultIfEmpty()
                                        join s in context.ServiceUserDepartments on t.userDepartmentId equals s.userDepartmentId into departmentGroup
                                        from s in departmentGroup.DefaultIfEmpty()
                                        select new IMSEntity
                                        {
                                            InwardID = i != null ? i.InwardID : null,
                                            InventoryReg_ID = t.InventoryReg_ID,
                                            AssetID = t.AssetID,
                                            Material_CategoryID = cat != null ? cat.Material_CategoryID : 0,
                                            Material_CategoryName = cat != null ? cat.Material_CategoryName : null,
                                            MaterialID = m != null ? m.MaterialID : null,
                                            MaterialName = m != null ? m.MaterialName : null,
                                            Purchase_Rate = t.Purchase_Rate,
                                            Asset_Cost = t.Asset_Cost,
                                            GRN_Number = t.GRN_Number,
                                            Quantity = t.Quantity,
                                            Model_Number = t.Model_Number,
                                            Serial_No = t.Serial_No,
                                            Makenm = t.Make,
                                            vendorName = v != null ? v.vendorName : tv != null ? tv.TempVendorName : null,
                                            ims_userDepartmentId = t != null ? t.userDepartmentId : null,
                                            userDepartmentName = s != null ? s.userDepartmentName : null,
                                            Location = t != null ? t.Location : null,
                                            Inward_ExpenseNature = i != null ? i.Inward_ExpenseNature : null,
                                            ExpenseNature = t.ExpenseNature,
                                            AssetGenerateDate = t.AssetGenerateDate,
                                        });


                    if (empid != null)
                    {
                        if (empid.Contains("DUM"))
                        {
                            if (role == "Inventory Manager")
                            {
                                InventoryDetails = InventoryDetails.Where(u => u.InventoryReg_ID.Contains("DUM"));
                            }
                            else
                            {
                                InventoryDetails = InventoryDetails.Where(u => u.InventoryReg_ID.Contains("DUM") && u.userDepartmentId == int.Parse(dept));
                            }
                        }
                        else
                        {
                            var inventoryList = InventoryDetails.ToList();
                            var locations = inventoryList.Select(s => s.vendorName).ToList();
                            int deptid = int.Parse(dept);
                            if (role == "Administrator")
                            {
                                InventoryDetails = InventoryDetails.Where(u => !u.InventoryReg_ID.Contains("DUM"));
                            }
                            else if (role == "Inventory Manager")
                            {
                                InventoryDetails = InventoryDetails.Where(u => !u.InventoryReg_ID.Contains("DUM") && u.ims_userDepartmentId == deptid);

                            }
                            else if (role == "Security Guard")
                            {
                                InventoryDetails = InventoryDetails.Where(u => !u.InventoryReg_ID.Contains("DUM") && u.Location == location);
                            }
                            else if (role == "Inventory Incharge" || role == "Receiver")
                            {
                                InventoryDetails = InventoryDetails.Where(u => !u.InventoryReg_ID.Contains("DUM") && u.Location == location && u.ims_userDepartmentId == deptid);
                            }
                            else
                            {

                                InventoryDetails = InventoryDetails.Where(u => !u.InventoryReg_ID.Contains("DUM") && u.ims_userDepartmentId == deptid);
                            }
                        }
                    }
                    var c = InventoryDetails.Count();
                    if (!String.IsNullOrEmpty(SearchValue) || !String.IsNullOrEmpty(SearchValue_ExpenseN) || !String.IsNullOrEmpty(SearchValue1) || searchdate != null)
                    {
                        String Searchby = form["Name"].ToString();

                        if (Searchby == "Asset_id")
                        {
                            countForsearch = 1;
                            InventoryDetails = InventoryDetails.Where(u => u.AssetID.Contains(SearchValue));
                        }
                        else if (Searchby == "Inv_department")
                        {

                            countForsearch = 1;
                            InventoryDetails = InventoryDetails.Where(u => u.userDepartmentName == SearchValue1);

IMS.Web/Views/Add_InventoryRegister/InventoryDetails.cshtml
@model IEnumerable<IMS.Models.IMSEntity>

@{
    string role = ViewBag.role;
    string empid = ViewBag.empid;
    string dept = ViewBag.department;
    string location = ViewBag.location;
    string inwardID = ViewBag.inwardID;
    string expense = ViewBag.expensenature;

    ViewBag.Title = "InventoryDetails";
    Layout = "~/Views/Shared/_Layout_IMS.cshtml";
}


<link href="~/assets/css/custom.css" rel="stylesheet" />
<div class="inventory-details invtry-details">
    <div class="d-flex align-items-center justify-content-between">
        <h5 class="content-title mb-3">Inventory Register Details</h5>
        <a class="back-btn d-flex" href="@Url.Action("Index", "Add_InventoryRegister")">
            <img class="mr-8" src="~/assets/images/icons/back-arrow.svg" /> Back
        </a>
    </div>
    <div class="card">
        <div class="row">
            <div class="col-md-12">
                <div class="card-body">
                    <div class="d-flex align-items-center asset-id">
                        @foreach (var item in Model)
                        {
                            <div>Asset ID: </div>
                            <div>
                                @Html.DisplayFor(modelitem => item.AssetID)
                            </div>
                        }
                    </div>
                    <table>
                        <thead>
                            <tr>
                                <th class="col-lg-2">Material Category Name</th>
                                <th class="col-lg-2">MaterialName</th>
                                <th class="col-lg-2">Expense Nature</th>
                                <th class="col-lg-2">GRN Number</th>
                                <th class="col-lg-2">Department Name</th>
                            </tr>
                        </thead>
                        <tr>
                            @foreach (var item in Model)
                            {
                                <td>
                                    @Html.DisplayFor(modelitem => item.Material_CategoryName)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelitem => item.MaterialName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelitem => item.ExpenseNature)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelitem => item.GRN_Number)
                                </td>
                                <td>

                                    @Html.DisplayFor(modelitem => item.userDepartmentName)
                                </td>
                            }
                        </tr>
                    </table>


                    <table>
                        <thead>
                            <tr>

                                <th class="col-lg-2">Purchase Rate</th>
                                <th class="col-lg-2">Asset Cost</th>
                                <th class="col-lg-2">Make</th>
                                <th class="col-lg-2">Serial No</th>
                                <th class="col-lg-2">Model No</th>
                            </tr>
                        </thead>
                        <tr>
                            @foreach (var item in Model)
                            {

                                <td>
                                    @Html.DisplayFor(modelitem => item.Purchase_Rate)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelitem => item.Asset_Cost)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelitem => item.Makenm)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelitem => item.Serial_No)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelitem => item.Model_Number)
                                </td>
                            }
                        </tr>
                    </table>

                    <table>
                        <thead>
                            <tr>
                                <th class="col-lg-2">Machine ID</th>
                                <th class="col-lg-2">RAM</th>
                                <th class="col-lg-2">HDD</th>
                                <th class="col-lg-2">OS</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelitem => item.MachineID)</td>
                                    <td>@Html.DisplayFor(modelitem => item.RAM)</td>
                                    <td>@Html.DisplayFor(modelitem => item.HDD)</td>
                                    <td>@Html.DisplayFor(modelitem => item.OS)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="../assets/libs/jquery/dist/jquery.min.js"></script>

IMS.Web/Views/Add_InventoryRegister/UploadInventoryRegister.cshtml
@{
    ViewBag.Title = "UploadInventoryRegister";
    Layout = "~/Views/Shared/_Layout_IMS.cshtml";
}
<link href="~/assets/css/custom.css" rel="stylesheet" />
<link href="~/Content/Common.css" rel="stylesheet" />
<div class="rightpanel-height">
    <div id="loader"></div>
    <h5 class="content-title mb-3">Upload Inventory Register</h5>
    <div class="card">
        <div class="card-body card-height">
            @using (Html.BeginForm("UploadInventoryRegister", "Add_InventoryRegister", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group mb-4 col-md-4">
                    <label for="file" class="form-label">Select an Excel file</label>
                    <input type="file" name="file" id="file" class="form-control" required />
                </div>

                <button type="submit" class="action-btn">Upload</button>
            }
            @if (ViewBag.Message != null)
            {
                <div class="alert alert-info">
                    @ViewBag.Message
                </div>
            }
        </div>
    </div>
</div>

<!-- Loader div -->
@*<div id="loader" style="display: none;">
        <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>*@

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>

<script>
    $(document).ready(function () {
        // Show loader when form is submitted
        $('form').on('submit', function () {
            $('#loader').show();
        });
    });
</script>